global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 5.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 20.0 #8.0-travis #3.0 # 4 zark20200602
   height: 20.0 #8.0-travis #3.0 #4 zark20200602
   resolution: 0.05
   transform_tolerance: 0.5 #0.5-travis #1.0
   map_type: costmap
   robot_radius: 0.27 #0.35 #0.3 #0.28 #0.23

# GlobalPlanner:        
#    allow_unknown: true 
   plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
   - {name: inflation_layer_global,     type: "costmap_2d::InflationLayer"}
