TebLocalPlannerROS:

 odom_topic: odom
 #odom_topic: /robot_pose_ekf/odom_combined
 map_frame: /map
 #map_frame: /odom_combined

 # Robot

 max_vel_x: 0.3 #0.6
 max_vel_x_backwards: 0.1 #0.15
 max_vel_theta: 0.6 #0.5 
 acc_lim_x: 0.4 
 acc_lim_theta: 0.25 #0.3 
 min_turning_radius: 0.0
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    types: "point"
    # radius: 0.28
#   vertices: [[-0.2, -0.205], [-0.2, 0.205], [0.256, 0.205], [0.324, 0.105], [0.324, -0.105], [0.256, -0.205]]  #OB_robot #zark


 # GoalTolerance
 xy_goal_tolerance: 0.5 #0.2 #0.15-travis #0.2
 yaw_goal_tolerance: 3.14 #0.2 #0.15-travis #0.5
 free_goal_vel: False

 # Trajectory

 teb_autosize: True
 dt_ref: 0.4 #0.3 #0.6 #0.3 #0.45 #0.45 yimu 规划器旨在根据期望的时间分辨率（参数dt_ref）来布置每两个连续的姿势 注意，实际分辨率不是固定/冻结的，因为优化器需要调整转换时间以寻求时间最优性
 dt_hysteresis: 0.04 #0.1 #0.06 #0.03 #0.1
 global_plan_overwrite_orientation: True #False #True #yimu
 global_plan_viapoint_sep: 0.5 #-1 #0.5 #-1
 max_global_plan_lookahead_dist: 3.0 #2.0 #5.0 #3.0
 feasibility_check_no_poses: 5
 allow_init_with_backwards_motion: False #True # zark

 # Obstacles

 min_obstacle_dist: 0.28 #0.35 #0.29 #0.25 
 inflation_dist: 1.0 #test
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 15 #3 #40 #40 #yimu
 costmap_converter_spin_thread: True
 costmap_converter_rate: 10

 # Optimization

 no_inner_iterations: 5 
 no_outer_iterations: 4 
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.05 #0.1default
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 1000 #400 #50
 weight_kinematics_turning_radius: 1 #200 #1
 weight_optimaltime: 1 #3 #0.5
 weight_obstacle: 1000 #50
 weight_viapoint: 16.0 #1.0 #5.0 #1
 weight_dynamic_obstacle: 10 # not in use yet
 selection_alternative_time_cost: False # not in use yet

 # Homotopy Class Planner

 enable_homotopy_class_planning: False
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4 #1 
 roadmap_graph_no_samples: 5 #指定为创建路线图而生成的样本数
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False
