
#---standard pioneer footprint---
#---(in meters)---
#robot_radius: 0.25


transform_tolerance: 0.2
map_type: costmap

obstacle_layer:
 enabled: true
 obstacle_range: 2.5
 raytrace_range: 2.5
 #inflation_radius: 0.25
 track_unknown_space: true
 combination_method: 1

 observation_sources: laser_scan_sensor d435_group_sensors  # d435i_sensor_1 d435i_sensor_2 # gdut
 laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true, clean_time: 30.0}
 d435_group_sensors:
    sensor_frame: base_link
    data_type: PointCloud2 
    topic: /merge_pcl2  # merge /cam_1/cam_1/depth/color/points + /camera/depth/color/points 
    marking: true
    clearing: true
    min_obstacle_height: 0.0
    max_obstacle_height: 1.0
    expected_update_rate: 0
#  d435i_sensor_1:   #gdut
#     sensor_frame: cam_1_link 
#     data_type: PointCloud2 
#     topic: /cam_1/cam_1/depth/color/points   # /cam_1/cam_1/depth/color/points  /camera/depth/color/points 
#     marking: true
#     clearing: true
#     min_obstacle_height: 0.0
#     max_obstacle_height: 1.0
#     expected_update_rate: 0
#  d435i_sensor_2:  #gdut
#     sensor_frame: cam_2_link 
#     data_type: PointCloud2 
#     topic: /cam_2/cam_2/depth/color/points    
#     marking: true
#     clearing: true
#     min_obstacle_height: 0.0
#     max_obstacle_height: 1.0
#     expected_update_rate: 0


inflation_layer:
  enabled:              true
  cost_scaling_factor:  6.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.30 # max. distance from an obstacle at which costs are incurred for planning paths.   # gdut original is 0.6

static_layer:
  enabled:              true
  map_topic:            "/map"
