local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
#  update_frequency: 10.0
#  publish_frequency: 10.0
  update_frequency: 3.0    #gdut
  publish_frequency: 3.0   #gdut
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  robot_radius: 0.25
  transform_tolerance: 0.5
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
